Attribute VB_Name = "BE_KeyCodes"
'//
'// BE_Keycodes enumerates all keys
'//

Public Enum BE_KEYCODE
    KEY_LBUTTON = 1                 ' Left mouse button
    KEY_RBUTTON = 2                 ' Right mouse button
    KEY_CANCEL = 3                  ' Control-break processing
    KEY_MBUTTON = 4                 ' Middle mouse button
    KEY_XBUTTON1 = 5                ' Windows 2000/XP X1 mouse button
    KEY_XBUTTON2 = 6                ' Windows 2000/XP X2 mouse button
    KEY_BACK = 8                    ' BACKSPACE key
    KEY_TAB = 9                     ' TAB key
    KEY_CLEAR = 12                  ' CLEAR key
    KEY_RETURN = 13                 ' ENTER key
    KEY_SHIFT = 16                  ' SHIFT key
    KEY_CONTROL = 17                ' CTRL key
    KEY_MENU = 18                   ' ALT key
    KEY_PAUSE = 19                  ' PAUSE key
    KEY_CAPITAL = 20                ' CAPS LOCK key
    KEY_KANA = 21                   ' IME Kana mode
    KEY_HANGUEL = 21                ' IME Hanguel mode
    KEY_HANGUL = 21                 ' IME Hangul mode
    KEY_JUNJA = 23                  ' IME Junja mode
    KEY_FINAL = 24                  ' IME Final mode
    KEY_HANJA = 25                  ' IME Hanja mode
    KEY_KANJI = 25                  ' IME Kanji mode
    KEY_ESCAPE = 27                 ' ESC key
    KEY_CONVERT = 28                ' IME Convert
    KEY_NONCONVER = 29              ' IME Nonconvert
    KEY_ACCEPT = 30                 ' IME Accept
    KEY_MODECHANGE = 31             ' IME Mode change request
    KEY_SPACE = 32                  ' SPACEBAR
    KEY_PRIOR = 33                  ' PAGE UP key
    KEY_NEXT = 34                   ' PAGE DOWN key
    KEY_END = 35                    ' END key
    KEY_HOME = 36                   ' HOME key
    KEY_LEFT = 37                   ' LEFT ARROW key
    KEY_UP = 38                     ' UP ARROW key
    KEY_RIGHT = 39                  ' RIGHT ARROW key
    KEY_DOWN = 40                   ' DOWN ARROW key
    KEY_SELECT = 41                 ' SELECT key
    KEY_PRINT = 42                  ' PRINT key
    KEY_EXECUT = 43                 ' EXECUTE key
    KEY_SNAPSHOT = 44               ' PRINT SCREEN key
    KEY_INSERT = 45                 ' INS key
    KEY_DELETE = 46                 ' DEL key
    KEY_HELP = 47                   ' HELP key
    KEY_KEY_0 = 48                  ' 0 key
    KEY_KEY_1 = 49                  ' 1 key
    KEY_KEY_2 = 50                  ' 2 key
    KEY_KEY_3 = 51                  ' 3 key
    KEY_KEY_4 = 52                  ' 4 key
    KEY_KEY_5 = 53                  ' 5 key
    KEY_KEY_6 = 54                  ' 6 key
    KEY_KEY_7 = 55                  ' 7 key
    KEY_KEY_8 = 56                  ' 8 key
    KEY_KEY_9 = 57                  ' 9 key
    KEY_KEY_A = 65                  ' A key
    KEY_KEY_B = 66                  ' B key
    KEY_KEY_C = 67                  ' C key
    KEY_KEY_D = 68                  ' D key
    KEY_KEY_E = 69                  ' E key
    KEY_KEY_F = 70                  ' F key
    KEY_KEY_G = 71                  ' G key
    KEY_KEY_H = 72                  ' H key
    KEY_KEY_I = 73                  ' I key
    KEY_KEY_J = 74                  ' J key
    KEY_KEY_K = 75                  ' K key
    KEY_KEY_L = 76                  ' L key
    KEY_KEY_M = 77                  ' M key
    KEY_KEY_N = 78                  ' N key
    KEY_KEY_O = 79                  ' O key
    KEY_KEY_P = 80                  ' P key
    KEY_KEY_Q = 81                  ' Q key
    KEY_KEY_R = 82                  ' R key
    KEY_KEY_S = 83                  ' S key
    KEY_KEY_T = 84                  ' T key
    KEY_KEY_U = 85                  ' U key
    KEY_KEY_V = 86                  ' V key
    KEY_KEY_W = 87                  ' W key
    KEY_KEY_X = 88                  ' X key
    KEY_KEY_Y = 89                  ' Y key
    KEY_KEY_Z = 90                  ' Z key
    KEY_LWIN = 91                   ' Left Windows key
    KEY_RWIN = 92                   ' Right Windows key
    KEY_APPS = 93                   ' Applications key
    KEY_SLEEP = 95                  ' Computer Sleep key
    KEY_NUMPAD0 = 96                ' Numeric keypad 0 key
    KEY_NUMPAD1 = 97                ' Numeric keypad 1 key
    KEY_NUMPAD2 = 98                ' Numeric keypad 2 key
    KEY_NUMPAD3 = 99                ' Numeric keypad 3 key
    KEY_NUMPAD4 = 100               ' Numeric keypad 4 key
    KEY_NUMPAD5 = 101               ' Numeric keypad 5 key
    KEY_NUMPAD6 = 102               ' Numeric keypad 6 key
    KEY_NUMPAD7 = 103               ' Numeric keypad 7 key
    KEY_NUMPAD8 = 104               ' Numeric keypad 8 key
    KEY_NUMPAD9 = 105               ' Numeric keypad 9 key
    KEY_MULTIPLY = 106              ' Multiply key
    KEY_ADD = 107                   ' Add key
    KEY_SEPARATOR = 108             ' Separator key
    KEY_SUBTRACT = 109              ' Subtract key
    KEY_DECIMAL = 110               ' Decimal key
    KEY_DIVIDE = 111                ' Divide key
    KEY_F1 = 112                    ' F1 key
    KEY_F2 = 113                    ' F2 key
    KEY_F3 = 114                    ' F3 key
    KEY_F4 = 115                    ' F4 key
    KEY_F5 = 116                    ' F5 key
    KEY_F6 = 117                    ' F6 key
    KEY_F7 = 118                    ' F7 key
    KEY_F8 = 119                    ' F8 key
    KEY_F9 = 120                    ' F9 key
    KEY_F10 = 121                   ' F10 key
    KEY_F11 = 122                   ' F11 key
    KEY_F12 = 123                   ' F12 key
    KEY_F13 = 124                   ' F13 key
    KEY_F14 = 125                   ' F14 key
    KEY_F15 = 126                   ' F15 key
    KEY_F16 = 127                   ' F16 key
    KEY_F17 = 128                   ' F17 key
    KEY_F18 = 129                   ' F18 key
    KEY_F19 = 130                   ' F19 key
    KEY_F20 = 131                   ' F20 key
    KEY_F21 = 132                   ' F21 key
    KEY_F22 = 133                   ' F22 key
    KEY_F23 = 134                   ' F23 key
    KEY_F24 = 135                   ' F24 key
    KEY_NUMLOCK = 144               ' NUM LOCK key
    KEY_SCROLL = 145                ' SCROLL LOCK key
    KEY_LSHIFT = 154                ' Left SHIFT key
    KEY_RSHIFT = 155                ' Right SHIFT key
    KEY_LCONTROL = 156              ' Left CONTROl key
    KEY_RCONTROL = 157              ' Right CONTROL key
    KEY_LMENU = 158                 ' Left MENU key
    KEY_RMENU = 159                 ' Right MENU key
    KEY_PLUS = 171                  ' Plus key (+)
    KEY_COMMA = 172                 ' Comma key (,)
    KEY_MINUS = 173                 ' Minus key (-)
    KEY_PERIOD = 174                ' Period key (.)
    KEY_ATTN = &HF6                 ' ATTN key
    KEY_CRSEL = &HF7                ' CrSel key
    KEY_EXSEL = &HF8                ' ExSel key
    KEY_EREOF = &HF9                ' Erase EOF key
    KEY_PLAY = &HFA                 ' Play key
    KEY_ZOOM = &HFB                 ' Zoom key
    KEY_PA1 = &HFD                  ' PA1 key
    KEY_OEM_CLEAR = &HFE            ' Clear key
    KEY_KEY_CODES_COUNT = &HFF      ' (Not a key) amount of keycodes
End Enum

Public Enum MouseCodes
    MOUSE_LEFT = 1                  ' Left Mouse Button
    MOUSE_RIGHT = 2                 ' Right Mouse Button
    MOUSE_MID = 4                   ' Mid Mouse Button
End Enum
